import type { QuestionSection } from "./types";

export const sections: Array<QuestionSection> = [
  {
    id: "01",
    title: "Project Snapshot",
    helper: "Basic context so we understand your business and who to coordinate with.",
    fields: [
      { key: "client_name", label: "Client name / company", type: "text" },
      { key: "contact_role", label: "Main contact + role", type: "text" },
      { key: "email_phone", label: "Email / phone", type: "text" },
      { key: "industry", label: "Business type / industry", type: "text" },
      { key: "current_website", label: "Current website", type: "text" },
      { key: "project_title", label: "Project name (working title)", type: "text" },
    ],
  },
  {
    id: "02",
    title: "What Are You Building?",
    helper: "Tell us your main business goal in plain language.",
    fields: [
      {
        key: "project_type",
        label: "Project type",
        type: "checkbox-group",
        options: [
          "Marketing website",
          "SaaS product",
          "Marketing site + SaaS app",
          "E-commerce",
          "Internal dashboard/tool",
          "Not sure yet",
        ],
      },
      {
        key: "core_goal",
        label: "Core goal (top 1-2)",
        type: "checkbox-group",
        options: [
          "Generate leads",
          "Increase sales/conversions",
          "Educate users",
          "Launch MVP quickly",
          "Improve existing UX/UI",
          "Rebrand / reposition",
        ],
      },
      {
        key: "success_metrics",
        label: "How do we measure success?",
        type: "textarea",
        placeholder: "e.g. 40 demo requests/month, 4% trial-to-paid conversion",
      },
    ],
  },
  {
    id: "03",
    title: "Scope and Deliverables",
    helper: "What must launch in V1 and what can wait for phase 2.",
    fields: [
      { key: "marketing_pages", label: "If website: pages needed", type: "textarea" },
      { key: "core_workflow", label: "If SaaS: core workflow", type: "textarea" },
      { key: "user_roles", label: "User roles needed", type: "text" },
      { key: "auth_required", label: "Authentication required", type: "text" },
      { key: "billing_model", label: "Billing needed", type: "text" },
      { key: "integrations", label: "Integrations needed", type: "text" },
      { key: "launch_features", label: "Key features at launch", type: "textarea" },
      { key: "mvp_future", label: "V1 vs phase 2", type: "textarea" },
    ],
  },
  {
    id: "04",
    title: "Audience and Positioning",
    helper: "Helps us design messaging and UX that matches your customers.",
    fields: [
      { key: "target_user", label: "Primary target user/customer", type: "text" },
      { key: "b2b_b2c", label: "B2B or B2C", type: "text" },
      { key: "user_level", label: "Beginner/intermediate/expert", type: "text" },
      { key: "pain_point", label: "Main pain point solved", type: "text" },
      { key: "alternatives", label: "Current alternatives", type: "textarea" },
      { key: "competitors", label: "Top competitors", type: "textarea" },
    ],
  },
  {
    id: "05",
    title: "Brand Direction",
    helper: "How your brand should feel to users.",
    fields: [
      { key: "brand_guidelines", label: "Brand guidelines", type: "textarea" },
      { key: "brand_words", label: "Brand personality words", type: "text" },
      {
        key: "tone",
        label: "Preferred tone",
        type: "checkbox-group",
        options: ["Corporate", "Friendly", "Bold", "Minimal", "Other"],
      },
      { key: "inspiration", label: "3-5 inspiration references", type: "textarea" },
      { key: "avoid_examples", label: "Examples to avoid", type: "textarea" },
    ],
  },
  {
    id: "06",
    title: "Content and Assets",
    helper: "What materials are ready today.",
    fields: [
      {
        key: "copy_status",
        label: "Copywriting status",
        type: "checkbox-group",
        options: ["Ready", "Need help"],
      },
      { key: "brand_assets", label: "Logo and brand assets", type: "textarea" },
      { key: "media_assets", label: "Screenshots/images/videos", type: "textarea" },
      { key: "legal_pages", label: "Legal pages required", type: "textarea" },
    ],
  },
  {
    id: "07",
    title: "Technical Requirements",
    helper: "Platform, integrations, compliance, and performance targets.",
    fields: [
      { key: "stack", label: "Preferred stack/platform", type: "text" },
      { key: "need_cms", label: "Need CMS", type: "text" },
      { key: "need_seo", label: "Need SEO setup", type: "text" },
      { key: "need_analytics", label: "Need analytics", type: "text" },
      { key: "accessibility", label: "Accessibility target", type: "text" },
      { key: "compliance", label: "Compliance/security constraints", type: "text" },
      { key: "performance", label: "Performance expectations", type: "textarea" },
    ],
  },
  {
    id: "08",
    title: "Timeline and Budget",
    helper: "Set realistic planning windows from day one.",
    fields: [
      { key: "launch_date", label: "Desired launch date", type: "text" },
      { key: "deadline_type", label: "Hard deadline or flexible", type: "text" },
      { key: "milestones", label: "Important milestones", type: "text" },
      { key: "budget", label: "Budget range", type: "text" },
      {
        key: "feedback_availability",
        label: "Team availability for feedback",
        type: "textarea",
      },
    ],
  },
  {
    id: "09",
    title: "Team and Decisions",
    helper: "Avoid approval bottlenecks and communication gaps.",
    fields: [
      { key: "stakeholders", label: "Stakeholders and final decision-maker", type: "textarea" },
      { key: "feedback_rounds", label: "Expected feedback rounds", type: "text" },
      { key: "communication_channel", label: "Preferred communication channel", type: "text" },
      { key: "meeting_cadence", label: "Meeting cadence", type: "text" },
    ],
  },
  {
    id: "10",
    title: "Post-Launch Needs",
    helper: "Define support expectations after launch.",
    fields: [
      { key: "maintenance", label: "Ongoing support/maintenance", type: "textarea" },
      { key: "ab_testing", label: "A/B testing and CRO needs", type: "textarea" },
      { key: "roadmap", label: "Future roadmap planning", type: "textarea" },
    ],
  },
  {
    id: "11",
    title: "Quick Priorities",
    helper: "Rank each priority from 1 (highest) to 5 (lowest).",
    fields: [
      { key: "priority_visual", label: "Visual polish / brand perception", type: "number" },
      { key: "priority_speed", label: "Fast launch speed", type: "number" },
      { key: "priority_conversion", label: "Conversion performance", type: "number" },
      { key: "priority_usability", label: "Product usability", type: "number" },
      { key: "priority_scalability", label: "Scalability for future features", type: "number" },
    ],
  },
  {
    id: "12",
    title: "Final Open Question",
    helper: "Anything else we should know before kickoff.",
    fields: [{ key: "final_notes", label: "Final notes", type: "textarea" }],
  },
];
